/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisResult: typeof import('./src/components/exams/ai/AnalysisResult.vue')['default']
    AppBreadcrumb: typeof import('./src/components/navigation/AppBreadcrumb.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DisabledExamCard: typeof import('./src/components/exams/DisabledExamCard.vue')['default']
    DisabledGroupCard: typeof import('./src/components/groups/DisabledGroupCard.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    DocumentUploader: typeof import('./src/components/exams/ai/DocumentUploader.vue')['default']
    ExportUsersModal: typeof import('./src/components/users/ExportUsersModal.vue')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/auth/ForgotPasswordForm.vue')['default']
    GenerationHistory: typeof import('./src/components/exams/ai/GenerationHistory.vue')['default']
    GenerationParameters: typeof import('./src/components/exams/ai/GenerationParameters.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InvoiceManagement: typeof import('./src/components/payments/InvoiceManagement.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    NotificationBell: typeof import('./src/components/notifications/NotificationBell.vue')['default']
    NotificationCard: typeof import('./src/components/notifications/NotificationCard.vue')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    NotificationToast: typeof import('./src/components/notifications/NotificationToast.vue')['default']
    Password: typeof import('primevue/password')['default']
    PaymentChart: typeof import('./src/components/charts/PaymentChart.vue')['default']
    PaymentForm: typeof import('./src/components/payments/PaymentForm.vue')['default']
    PaymentMethodsManagement: typeof import('./src/components/payments/PaymentMethodsManagement.vue')['default']
    PlanCard: typeof import('./src/components/plans/PlanCard.vue')['default']
    PlanComparison: typeof import('./src/components/plans/PlanComparison.vue')['default']
    PlanLimitModal: typeof import('./src/components/plans/PlanLimitModal.vue')['default']
    PlanSelectionModal: typeof import('./src/components/plans/PlanSelectionModal.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    ProfileEditForm: typeof import('./src/components/profile/ProfileEditForm.vue')['default']
    ProfilePreferences: typeof import('./src/components/profile/ProfilePreferences.vue')['default']
    ProfileStats: typeof import('./src/components/profile/ProfileStats.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    ResetPasswordForm: typeof import('./src/components/auth/ResetPasswordForm.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RoleBasedNavigation: typeof import('./src/components/navigation/RoleBasedNavigation.vue')['default']
    RoleRedirect: typeof import('./src/components/navigation/RoleRedirect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
